// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByTqS0py4y1FsJ38lFbk_XmcxjxKqoi3k',
    appId: '1:923726587011:web:686509976ec7318233a7b6',
    messagingSenderId: '923726587011',
    projectId: 'aquatrack-cb196',
    authDomain: 'aquatrack-cb196.firebaseapp.com',
    databaseURL: 'https://aquatrack-cb196-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquatrack-cb196.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4o_u96susUQY4YMUGnGdsANZ2DzQ96tI',
    appId: '1:923726587011:android:4d6c102d2e3ea75c33a7b6',
    messagingSenderId: '923726587011',
    projectId: 'aquatrack-cb196',
    databaseURL: 'https://aquatrack-cb196-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquatrack-cb196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8z4SI43c0cUW9lh3K9oL18cXYqOBzhuo',
    appId: '1:923726587011:ios:5d33b04f389772c233a7b6',
    messagingSenderId: '923726587011',
    projectId: 'aquatrack-cb196',
    databaseURL: 'https://aquatrack-cb196-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquatrack-cb196.appspot.com',
    iosBundleId: 'com.example.waterFlowApp',
  );
}
